### ISSUE TITLE
email body toJSON has issue

### ISSUE THREAD

**Issue by rohan-git** [rohan-git/MERN_Application_Progress#11]
error SyntaxError: Unexpected token < in JSON at position 0
[0]     at JSON.parse (<anonymous>)
[0]     at C:\Users\rohan.mehta\Reactjs\FullstackReactCode\new_stuff\node_modules\sendgrid\lib\sendgrid.js:96:48
[0]     at IncomingMessage.<anonymous> (C:\Users\rohan.mehta\Reactjs\FullstackReactCode\new_stuff\node_modules\sendgrid-rest\lib\client.js:112:9)
[0]     at IncomingMessage.emit (events.js:164:20)
[0]     at endReadableNT (_stream_readable.js:1054:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)

At this commit : 

https://github.com/rohan-git/MERN_Application_Progress/commit/4be1bcee6b98750775aa1589ac6d9778211bfa9e

**Comment by rohan-git** [comment]
this is fixed in 9c2d0e2dfd4bce2c038a4d540af21432ef37e2fc
